export default function getKZCities() {
  return [
    {engName: 'Almaty', rusName: 'Алматы'},
    {engName: 'Astana', rusName: 'Астана'},
    {engName: 'Shymkent', rusName: 'Шымкент'},
    {engName: 'Aktau', rusName: 'Актау'},
    {engName: 'Aktobe', rusName: 'Актобе'},
    {engName: 'Atyrau', rusName: 'Атырау'},
    {engName: 'Karaganda', rusName: 'Караганда'},
    {engName: 'Kokshetau', rusName: 'Кокшетау'},
    {engName: 'Kostanay', rusName: 'Костанай'},
    {engName: 'Kyzylorda', rusName: 'Кызылорда'},
    {engName: 'Pavlodar', rusName: 'Павлодар'},
    {engName: 'Petropavl', rusName: 'Петропавловск'},
    {engName: 'Semey', rusName: 'Семей'},
    {engName: 'Taldykorgan', rusName: 'Талдыкорган'},
    {engName: 'Taraz', rusName: 'Тараз'},
    {engName: 'Oral', rusName: 'Уральск'},
    {engName: 'Oskemen', rusName: 'Усть-Каменогорск'},
    {engName: 'Shymkent', rusName: 'Шымкент'},
    {engName: 'Jezkazgan', rusName: 'Жезказган'},
    {engName: 'Zyryanovsk', rusName: 'Зыряновск'},
    {engName: 'Taraz', rusName: 'Тараз'},
  ]
}